services:
  - type: web
    name: wheretoi-webapp
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: off
    healthCheckPath: /api/health
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: WHERETOI_DATABASE_URL
        sync: false
      - key: PORT
        value: "10000"
