export function getDomRefs() {
  return {
    tabs: document.querySelectorAll(".tab"),
    views: document.querySelectorAll(".view"),
    title: document.querySelector("#view-title"),
    statusText: document.querySelector("#map-status"),
    searchInput: document.querySelector("#location-search"),
    searchCard: document.querySelector("#search-card"),
    toggleSearchButton: document.querySelector("#toggle-search"),
    directionsButton: document.querySelector("#directions-button"),
    detailsCard: document.querySelector("#details-card"),
    mapPanel: document.querySelector("#map-panel"),
    mapElement: document.querySelector("#map"),
    closeDetailsButton: document.querySelector("#close-details"),
    locateButtons: [document.querySelector("#locate-button"), document.querySelector("#find-near-me")],
    featureFilterInputs: document.querySelectorAll("#feature-filters input[type='checkbox']"),
    sortSelect: document.querySelector("#toilet-sort"),
    resultsSummary: document.querySelector("#results-summary"),
    resultsList: document.querySelector("#toilet-results"),
    resetMapButton: document.querySelector("#reset-map"),
    mapSurveyCleanYesButton: document.querySelector("#map-survey-clean-yes"),
    mapSurveyCleanNoButton: document.querySelector("#map-survey-clean-no"),
    mapSurveyStatus: document.querySelector("#map-survey-status"),
    activatePassButton: document.querySelector("#activate-pass"),
    activationStatus: document.querySelector("#activation-status"),
    surveyModal: document.querySelector("#cleanliness-survey-modal"),
    surveyCleanYesButton: document.querySelector("#survey-clean-yes"),
    surveyCleanNoButton: document.querySelector("#survey-clean-no"),
    closeSurveyButton: document.querySelector("#close-survey"),
    surveyQuestion: document.querySelector("#cleanliness-survey-question"),
    surveyStatus: document.querySelector("#survey-status"),
    walletBalance: document.querySelector("#wallet-balance"),
    subscriptionPlan: document.querySelector("#subscription-plan"),
    monthlyTicketsLeft: document.querySelector("#monthly-tickets-left"),
    accessHistoryList: document.querySelector("#access-history-list"),
    ticketToiletName: document.querySelector("#ticket-toilet-name"),
    ticketPrice: document.querySelector("#ticket-price")
  };
}
